### ISSUE TITLE
I disagree with the monkey-banana parsing

### ISSUE THREAD

**Issue by polycopter** [cytora/pycon-nlp-in-10-lines#17]
it seems like you have parsed it like:
monkeys ate a bunch. what kind of bunch? an of-delicious-bananas bunch.

I would have parsed it like:
monkeys ate bananas. what kind of bananas? a-bunch-of-delicious bananas.

i suppose i should mention that i don't really know anything beyond what i learned in English class in 7th & 8th grades (approximately)... and that "knowledge" is pretty rusty by now, at best.

**Comment by andrazhribernik** [comment]
Hi @polycopter,

Could you please be more specific and point me to a specific part of the tutorial/notebook where this could be improved. If this issue is related to the way spaCy does text parsing, [spaCy repo](https://github.com/explosion/spaCy) might be a better place to open an issue.

Andraz

**Comment by andrazhribernik** [comment]
@polycopter since I haven't heard back from you, I will close this issue.

**Comment by polycopter** [comment]
I have a notion that the" specific part of the tutorial" is the only part that contains "monkeys ate a bunch of delicious bananas"; I'm a bit mystified why you couldn't find it. I admit I didn't get all the way through. As far as whether it is spaCy or an invented example, I have no idea; I haven't installed spaCy yet. Unfortunately I don't know how to make my comment any clearer.
