### ISSUE TITLE
Using pycon-notebooks at spacy-notebooks

### ISSUE THREAD

**Issue by bhargavvader** [cytora/pycon-nlp-in-10-lines#21]
Hello! I've been trying to aggregate all the spaCy tutorials in the form of jupyter notebooks, when I came across your repo. The notebooks here are awesome, and I wanted to know if it's ok if I add them to this [repo](https://github.com/explosion/spacy-notebooks).

They'll be credited appropriately, obviously. 

Thanks again for the notebooks and your help!

**Comment by andrazhribernik** [comment]
Sure. It would be nice if you can add a link to this repo, otherwise feel free to use them.

**Comment by bhargavvader** [comment]
Will add a link pointing here as well. :)
